server.port=8081
spring.application.name=TaskManager
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://MysqlContainer:3306/Task_manager1
spring.datasource.username=root
spring.datasource.password=12385678
spring.jpa.hibernate.ddl-auto=update
